# Generated by Django 4.1.3 on 2022-11-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation", options={"ordering": ["rental_id"]},
        ),
    ]
