# Generated by Django 4.1.3 on 2022-11-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_alter_reservation_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="rental", options={"ordering": ["name"]},),
        migrations.AlterModelOptions(
            name="reservation", options={"ordering": ["rental"]},
        ),
        migrations.RenameField(
            model_name="reservation", old_name="rental_id", new_name="rental",
        ),
    ]
